version: '3'

services:
  artifactory:
    build: .
    container_name: artifactory
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=8082
    ports:
      - 8082:8082 # for router communication
      - 8081:8081 # for artifactory communication
    volumes:
      - /opt/jfrog/jfrog:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  nginx:
    image: releases-docker.jfrog.io/jfrog/nginx-artifactory-pro:7.39.4
    container_name: nginx
    depends_on:
      - artifactory
    network_mode: service:artifactory
    volumes:
      - /opt/jfrog/nginx:/var/opt/jfrog/nginx
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ART_BASE_URL=http://localhost:8082
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  postgres:
    image: releases-docker.jfrog.io/postgres:13.4-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=__REPLACE_POSTGRES_PASSWORD__
    ports:
      - 5432:5432
    volumes:
      - /opt/jfrog/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
